### PR TITLE
Carbons4Adium, Adium plugin containing only the carbons libpurple plugin

### PR DESCRIPTION
**Pull request by arahlin**
This is a version of your plugin that contains only `carbons`, for the use case when encryption is not necessary (#8).  Thought I'd submit this as a pull request to incorporate as a branch of your main repository.  I've tested that this builds and runs on my laptop (with OSX 10.12).

### CODE REVIEW

**Comment by shtrom** [comment]
Hey, thanks for that!

I'd be of the opinion that encryption is always necessary, but I'm happy to merge this in some form.

I think the best would be to be able to parametrise the build so it we can choose what to build in.

I'm a bit time poor at the moment, but I'll try to have a look. For a quick glance, it looks like you created a whole new plugin with a different name. Perhaps the easiest is to have a separate branch.

**Comment by arahlin** [comment]
No problem!  Your project was straightforward enough to follow, thought I'd give this a shot.

I did indeed create this on a separate branch on my fork, mostly because I couldn't get lurch to build properly on my machine... parametrising the build might be better though, easier to maintain than two separate branches.

**Comment by shtrom** [comment]
Yeah, I'll see what we can do.

Out of curiousity, though, what failed when trying to build lurch? We may have a bug hiding there, too.

**Comment by arahlin** [comment]
Sorry, I totally missed your question here.  IIRC I just didn't have some of the right dependencies to be able to build lurch correctly.  I didn't want to go down the rabbit hole of getting that to work, so I just extracted the carbon bits into a separate branch...

**Comment by shtrom** [comment]
Hey, would you mind trying to build the branch at from #12? I've found a bunch of dependency issues that I had to fix, and I wonder if that's the same ones you ran into.

**Comment by shtrom** [comment]
Ideally, if we want to keep going the carbons-only way I would prefer a build that can be parametrised to selectively disable Lurch, rather than a hard removal as in this PR.

With https://github.com/shtrom/Lurch4Adium/issues/8#issuecomment-429631555, I will close this PR, as it seems we can enable Carbons only (and disable Lurch), even if the Lurch code is coming for a ride.

**Pull request closed without merging**
